var cruiseShips = [
"Achille Lauro",
"Adonia",
"Adriana",
"Adventure of the Seas",
"Aegean Odyssey",
"Aegean Paradise",
"AIDAaura",
"AIDAbella",
"AIDAblu",
"AIDAcara",
"AIDAdiva",
"AIDAluna",
"AIDAmar",
"AIDAperla",
"AIDAprima",
"AIDAsol",
"AIDAstella",
"AIDAvita",
"Albatros",
"Allure of the Seas",
"Amadea",
"American Eagle",
"American Glory",
"Amerikanis",
"Amsterdam",
"RMS Andes",
"Aranui 3",
"Arcadia",
"Arosa Star",
"Arosa Sun",
"Artania",
"Assedo",
"Astor",
"Asuka II",
"Athena",
"Atlantic Star",
"Aurora",
"Aurora Star",
"Ausonia",
"Azamara Journey",
"Azamara Quest",
"Azura",
"Bahamas Celebration",
"Balmoral",
"Barcelona",
"Belofin I",
"Bianca C",
"The Big Red Boat",
"Birka Stockholm",
"Black Watch",
"Blenheim (3)",
"Bore",
"Boudicca",
"Braemar",
"Brahe",
"Bremen",
"Brilliance of the Seas",
"Britannia",
"Caly",
"Canberra",
"Cape Cod Light",
"Cape May Light",
"Caribbean Princess",
"Carnival Breeze",
"Carnival Conquest",
"Carnival Destiny",
"Carnival Dream",
"Carnival Ecstasy",
"Carnival Elation",
"Carnival Fantasy",
"Carnival Fascination",
"Carnival Freedom",
"Carnival Glory",
"Carnival Imagination",
"Carnival Inspiration",
"Carnival Legend",
"Carnival Liberty",
"Carnival Magic",
"Carnival Miracle",
"Carnival Paradise",
"Carnival Pride",
"Carnival Sensation",
"Carnival Spirit",
"Carnival Splendor",
"Carnival Sunshine",
"Carnival Triumph",
"Carnival Valor",
"Carnival Victory",
"Carnival Vista",
"Carnivale",
"Celebration",
"Celebrity Century",
"Celebrity Constellation",
"Celebrity Eclipse",
"Celebrity Equinox",
"Celebrity Infinity",
"Celebrity Millennium",
"Celebrity Reflection",
"Celebrity Silhouette",
"Celebrity Solstice",
"Celebrity Summit",
"Celebrity Xpedition",
"Celestyal Crystal",
"China Star",
"Clio",
"Clipper Adventurer",
"Clipper Odyssey",
"Club Med 2",
"Constitution",
"Coral",
"Coral Princess",
"Costa Allegra",
"Costa Atlantica",
"Costa Pacifica",
"Carla Costa",
"Costa Classica",
"Costa Concordia",
"Costa Deliziosa",
"Costa Diadema",
"Costa Fortuna",
"Costa Fascinosa",
"Costa Favolosa",
"Costa Luminosa",
"Costa Magica",
"Costa Mediterranea",
"Costa neoRiviera",
"Costa neoRomantica",
"Costa Serena",
"Costa Victoria",
"Costa Voyager",
"Crown Princess",
"Crystal Serenity",
"Crystal Symphony",
"Cunard Ambassador",
"Daphne",
"Dawn Princess",
"Delphin",
"Diamond Princess",
"Discovery",
"Disney Dream",
"Disney Fantasy",
"Disney Magic",
"Disney Wonder",
"Dolphin",
"Dolphin IV",
"Dreamward",
"easyCruiseOne",
"The Emerald",
"Emerald Princess",
"Empress",
"Empress Star",
"Empress of Canada",
"Enchanted Capri",
"Enchanted Isle",
"Enchanted Seas",
"Enchantment of the Seas",
"Enrico C. / Enrico Costa",
"Eugenio C. / Eugenio Costa",
"Eurodam",
"Europa",
"Explorer of the Seas",
"Fair Princess",
"Fairland",
"Fairsea",
"Fairsky",
"Fairstar",
"Fifty Years of Victory",
"Fram",
"Fort Victoria",
"Franca C",
"RMS Franconia",
"Fedor Shalyapin",
"Freedom of the Seas",
"Freewinds",
"Gemini",
"Golden Iris",
"Golden Princess",
"Grand Celebration",
"Grand Princess",
"Grandeur of the Seas",
"Gripsholm",
"Genting Dream",
"Hamburg",
"Hanseatic",
"Harmony of the Seas",
"Harmony Princess",
"Hebridean Princess",
"Henna",
"Homeric",
"Horizon",
"Independence of the Seas",
"Independence",
"Insignia",
"Island Escape",
"Island Princess",
"Island Sky",
"Ivan Franko",
"Jewel of the Seas",
"Klavdiya Yelanskaya",
"Knyaz Vladimir",
"Koningsdam",
"Kristina Regina",
"Kungsholm",
"L'Amant",
"L'Austral",
"Le Boréal",
"Le Diamant",
"Le Levant",
"Le Ponant",
"Legacy",
"Legend of the Seas",
"Leonardo da Vinci",
"Leisure World",
"Leonid Sobinov",
"Liberty of the Seas",
"Louis Olympia",
"SS Lurline (1931)",
"Lyubov Orlova",
"Maasdam",
"Magellan",
"Majesty of the Seas",
"Macau Success",
"Mandalay",
"Marco Polo",
"Marina",
"Mariner of the Seas",
"RMS Mauretania",
"RMS Mauretania II",
"Maxim Gorkiy",
"Phoenix Reisen",
"Mein Schiff 1",
"Mein Schiff 2",
"Mein Schiff 3",
"Mein Schiff 4",
"Mein Schiff 5",
"Mikhail Lermontov",
"Midnatsol",
"Minerva",
"Mona Lisa",
"Monarch",
"Monterey",
"MSC Armonia",
"MSC Divina",
"MSC Fantasia",
"MSC Lirica",
"MSC Magnifica",
"MSC Melody",
"MSC Musica",
"MSC Opera",
"MSC Orchestra",
"MSC Poesia",
"MSC Sinfonia",
"MSC Splendida",
"National Geographic Endeavour",
"National Geographic Explorer",
"Nautica",
"Navigator of the Seas",
"Nieuw Amsterdam",
"Noordam",
"Nordic Empress",
"Nordkapp",
"Nordlys",
"Nordnorge",
"SS Norway",
"Norwegian Bliss",
"Norwegian Dawn",
"Norwegian Dream",
"Norwegian Epic",
"Norwegian Escape",
"Norwegian Getaway",
"Norwegian Gem",
"Norwegian Jade",
"Norwegian Jewel",
"Norwegian Pearl",
"Norwegian Spirit",
"Norwegian Sky",
"Norwegian Star",
"Norwegian Sun",
"Norwegian Breakaway",
"Oasis of the Seas",
"Ocean Atlantic",
"Ocean Countess",
"Ocean Dream",
"MV Ocean Dream",
"Ocean Endeavour",
"Ocean Life",
"RMS Olympic",
"Ocean Majesty",
"Ocean Mist",
"Ocean Star Pacific",
"Oceana",
"OceanBreeze",
"Oceanic",
"Oceanic Discoverer",
"Oceanic Independence",
"Oceanos",
"Ocean Pearl",
"Ocean Princess",
"Ola Esmeralda",
"Oosterdam",
"Oranje",
"Oriana",
"Orient Queen",
"Oriental Dragon",
"Orion",
"Pacific",
"Pacific Aria",
"Pacific Dawn",
"Pacific Eden",
"Pacific Explorer",
"Pacific Jewel",
"Pacific Pearl",
"Pacific Princess",
"Pacific Star",
"Pacific Venus",
"Pallas Athena",
"Palm Beach Princess",
"Paul Gauguin",
"Pearl Seaways",
"Polaris",
"Porto",
"Pride of America",
"Princess Daphne",
"Prinsendam",
"Quantum of the Seas",
"Queen Mary 2",
"Queen Victoria",
"Queen Elizabeth",
"Radiance of the Seas",
"Regal Empress",
"Regatta",
"Regent Sea",
"Rembrandt",
"Renaissance",
""Royal Canara cruises"",
"Rhapsody of the Seas",
"RIO",
"Ritz Carlton",
"Riviera",
"Rotterdam",
"Royal Princess",
"Regal Princess",
"Royal Clipper",
"Royal Pacific",
"Ruby Princess",
"Running on Waves",
"Ryndam",
"Saga Rose",
"Saga Ruby",
"Saga Sapphire",
"Salamis Glory",
"Sally Albatross",
"Sapphire",
"Sapphire Princess",
"Sea Breeze",
"Sea Cloud",
"Sea Cloud II",
"Sea Diamond",
"Sea Explorer",
"Sea Princess",
"Seabourn Odyssey",
"Seabourn Sojourn",
"Seabourn Quest",
"Seabourn Spirit",
"SeaDream I",
"SeaDream II",
"SeaWind Crown",
"Serenade of the Seas",
"Serenissima",
"Seven Seas Mariner",
"Seven Seas Navigator",
"Seven Seas Voyager",
"Silver Cloud",
"Silver Explorer",
"Silver Shadow",
"Silver Wind",
"Silver Whisper",
"Silver Spirit",
"Siritara Ocean Queen",
"Skorpios I",
"Skorpios II",
"Skorpios III",
"Sovereign",
"Spirit of Adventure",
"Spirit of Alaska",
"Spirit of Columbia",
"Spirit of Discovery",
"Spirit of Endeavour",
"Spirit of Glacier Bay",
"Spirit of Oceanus",
"Spirit of Yorktown",
"Spirit of '98",
"Splendour of the Seas",
"Star Breeze",
"Star Clipper",
"Star Flyer",
"Star Legend",
"Star Pisces",
"Star Pride",
"Star Princess",
"Statendam",
"Stella Polaris",
"SS Stella Solaris",
"Sun 11",
"Sun Princess",
"Sun Vista",
"SuperStar Aquarius",
"SuperStar Gemini",
"SuperStar Libra",
"SuperStar Virgo",
"Svea Corona",
"Taras Shevchenko",
"The Calypso",
"Thomson Celebration",
"Thomson Dream",
"Thomson Majesty",
"Thomson Spirit",
"TUI Discovery",
"Turama",
"SS Uganda",
"Van Gogh",
"Veendam",
"Ventura",
"Viking Sea",
"Viking Sky",
"Viking Star",
"Vision of the Seas",
"Vistamar",
"Volendam",
"Voyager of the Seas",
"Voyager",
"Westerdam",
"Wind Song",
"Wind Spirit",
"Wind Star",
"Wind Surf",
"The World",
"World Discoverer",
"World Odyssey",
"Xpedition",
"Yamal",
"Yankee Clipper",
"Yorktown",
"Zaandam",
"Zenith",
"Zuiderdam",
];
