var knots = [
"Adjustable Bend",
"Adjustable Grip Hitch",
"Albright Special",
"Alternate Ring Hitching",
"Anchor Bend",
"Angler's Loop",
"Arbor Knot",
"Artillery Loop",
"Ashley's Bend",
"Ashley's Stopper Knot",
"Axle Hitch",
"Bachmann Knot",
"Bag Knot",
"Bait Loop",
"Bale Sling Hitch",
"Bale Sling Hitch Or Strap Hitch",
"Barrel Hitch",
"Barrel Knot",
"Barrel Sling",
"Basket Weave Knot",
"Becket Hitch",
"Beer Knot",
"Bimini Twist",
"Blackwall Hitch",
"Blake's Hitch",
"Blood Knot",
"Blood Loop Knot",
"Boa Knot",
"Boling Knot",
"Boom Hitch",
"Bottle Sling",
"Bourchier Knot",
"Bowen Knot",
"Bowline",
"Bowline On A Bight",
"Bumper Knot",
"Bunny Ears",
"Buntline Hitch",
"Butterfly Bend",
"Butterfly Coil",
"Butterfly Loop",
"Carrick Bend",
"Carrick Bend Loop",
"Carrick Mat",
"Cat's Paw",
"Catshank",
"Celtic Button Knot",
"Chain Sinnet",
"Chain Stitch",
"Chair Knot",
"Chinese Button Knot",
"Cleat Hitch",
"Clinch Knot",
"Clove Hitch",
"Common Whipping",
"Constrictor Knot",
"Continuous Ring Hitching",
"Corned Beef Knot",
"Cow Hitch",
"Cow Hitch And Bowline",
"Cowboy Bowline",
"Cross Constrictor Knot",
"Crown Knot",
"Diagonal Lashing",
"Diamond Knot",
"Directional Figure Eight",
"Distel Hitch",
"Dogshank",
"Double Anchorman Knot",
"Double Bowline",
"Double Carrick Bend",
"Double Constrictor Knot",
"Double Englishman's Knot",
"Double Figure Eight",
"Double Figure Eight Bend",
"Double Figure-eight Loop",
"Double Fisherman's Knot",
"Double Loop",
"Double Overhand Knot",
"Double Overhand Noose",
"Double Pile Hitch",
"Double Sheet Bend",
"Double Windsor",
"Dropper Loop",
"Dutch Marine Bowline",
"Egg Loop",
"Englishman's Knot",
"Eskimo Bowline",
"European Death Knot",
"Eye Splice",
"Falconer's Knot",
"Farmer's Loop",
"Farrimond Friction Hitch",
"Fiador Knot",
"Figure-eight Knot",
"Figure-eight Loop",
"Figure-of-nine Loop",
"Fireman's Chair Knot",
"Fisherman's Bend",
"Fisherman's Knot",
"Flemish Bend",
"Flemish Knot",
"French Bowline",
"Friendship Knot",
"Friendship Knot Loop",
"Garda Hitch",
"Girth Hitch",
"Gordian Knot",
"Granny Knot",
"Grantchester Knot",
"Grapevine Knot",
"Grief Knot",
"Gripping Sailor's Hitch",
"Ground-line Hitch",
"Hackamore",
"Half Blood Knot",
"Half Hitch",
"Half-windsor Knot",
"Halter Hitch",
"Halyard Bend",
"Handcuff Knot",
"Hangman's Knot",
"Hangman's Noose",
"Harness Bend",
"Harness Hitch",
"Heaving Line Bend",
"Heraldic Knot",
"Highpoint Hitch",
"Highwayman's Hitch",
"Hitching Tie",
"Honda Knot",
"Hoxton Knot",
"Hunter's Bend",
"Icicle Hitch",
"Improved Clinch Knot",
"In-line Figure-eight Loop",
"Inline Figure-eight Loop",
"Italian Hitch",
"Jack Ketch's Knot",
"Jamming Knot",
"Jug Sling",
"Jury Mast Knot",
"Karash Double Loop",
"Killick Hitch",
"Klemheist Knot",
"Knife Lanyard Knot",
"Knot Of Isis",
"Knute Hitch",
"Lariat Loop",
"Lark's Foot",
"Left-hand Bowline",
"Ligature Knot",
"Lighterman's Hitch",
"Lineman's Loop",
"Lissajous Knot",
"Lobster Buoy Hitch",
"Magnus Hitch",
"Manharness Knot",
"Marlinespike Hitch",
"Matthew Walker Knot",
"Midshipman's Hitch",
"Miller's Knot",
"Monkey's Fist",
"Mountaineer's Coil",
"Munter Hitch",
"Nail Knot",
"Noose",
"Offset Figure-eight Bend",
"One-sided Overhand Bend",
"Ossel Hitch",
"Overhand Bend",
"Overhand Knot",
"Overhand Knot With Draw-loop",
"Overhand Loop",
"Overhand Noose",
"Oysterman's Stopper Knot",
"Packer's Knot",
"Palomar Knot",
"Pile Hitch",
"Pipe Hitch",
"Poldo Tackle",
"Portuguese Bowline",
"Portuguese Whipping",
"Power Cinch",
"Pratt Knot",
"Pretzel Link Knot",
"Prusik Knot",
"Quick-release Knot",
"Racking Bend",
"Reef Knot",
"Reever Knot",
"Rigger's Bend",
"Rigid Double Splayed Loop In The Bight",
"Ring Bend",
"Ring Hitch",
"Ring Knot",
"Ringbolt Hitching",
"Rolling Hitch",
"Rosendahl Bend",
"Round Lashing",
"Round Turn",
"Round Turn And Two Half-hitches",
"Round Turn Bowline",
"Running Bowline",
"Running Highwayman's Hitch",
"Running Knot",
"Sailor's Hitch",
"Sailor's Knot",
"Savoy Knot",
"Shear Lashing",
"Sheepshank",
"Sheet Bend",
"Shoelace Knot",
"Shroud Knot",
"Siberian Hitch",
"Simple Knot",
"Simple Simon Under",
"Single Carrick Bend",
"Single Hitch",
"Slip Knot",
"Slipped Buntline Hitch",
"Slipped Half Hitch",
"Slippery Eight Loop",
"Slippery Hitch",
"Snell Knot",
"Snuggle Hitch",
"Span Loop",
"Spanish Bowline",
"Splice",
"Square Knot",
"Square Lashing",
"Square Turk's Head",
"Stein Knot",
"Stevedore Knot",
"Strangle Knot",
"Strap Hitch",
"Surgeon's Knot",
"Surgeon's Loop",
"Tape Knot",
"Tarbuck Knot",
"Taut-line Hitch",
"Tensionless Hitch",
"Tent Hitch",
"Thief Knot",
"Threefoil Knot",
"Thumb Knot",
"Timber Hitch",
"Tom Fool's Knot",
"Transom Knot",
"Trefoil Knot",
"Trident Loop",
"Trilene Knot",
"Triple Bowline",
"Triple Crown Knot",
"Triple Fisherman's Knot",
"Trucker's Hitch",
"True Lover's Knot",
"Tugboat Hitch",
"Turle Knot",
"Twined Turk's Head",
"Two Half-hitches",
"Two Strand Overhand Knot",
"Underhand Knot",
"Underwriter's Knot",
"Uni Knot",
"Versatackle Knot",
"Vibration-proof Hitch",
"Wagoner's Hitch",
"Wall And Crown Knot",
"Water Bowline",
"Water Knot",
"Waterman's Knot",
"West Country Whipping",
"Windsor Knot",
"Yosemite Bowline",
"Zeppelin Bend",
"Zeppelin Loop",
];
